<?xml version="1.0"?>
<ArkServerProfile xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ProfileID>cb2c549f-5976-4198-92d2-984000d235e8</ProfileID>
  <ProfileName>Ark Valyria By Saenyra</ProfileName>
  <InstallDirectory>C:\Servidores\Ark Valyria</InstallDirectory>
  <LastInstalledVersion>295.107</LastInstalledVersion>
  <ServerName>Ark Valyria By Saenyra</ServerName>
  <ServerPassword />
  <AdminPassword>260194</AdminPassword>
  <SpectatorPassword />
  <ServerConnectionPort>7777</ServerConnectionPort>
  <ServerPort>27015</ServerPort>
  <ServerIP>192.168.0.15</ServerIP>
  <UseRawSockets>false</UseRawSockets>
  <EnableBanListURL>false</EnableBanListURL>
  <BanListURL />
  <MaxPlayers>20</MaxPlayers>
  <EnableKickIdlePlayers>true</EnableKickIdlePlayers>
  <KickIdlePlayersPeriod>3600</KickIdlePlayersPeriod>
  <RCONEnabled>false</RCONEnabled>
  <RCONPort>32330</RCONPort>
  <RCONServerGameLogBuffer>600</RCONServerGameLogBuffer>
  <AdminLogging>false</AdminLogging>
  <ServerMap>/Game/Mods/1404089637/LostContinent</ServerMap>
  <TotalConversionModId />
  <ServerModIds>621154190,849985437,731604991,919470289,1191739191,814833973,819857895</ServerModIds>
  <EnableExtinctionEvent>false</EnableExtinctionEvent>
  <AutoSavePeriodMinutes>15</AutoSavePeriodMinutes>
  <MOTD />
  <MOTDDuration>20</MOTDDuration>
  <DisableValveAntiCheatSystem>false</DisableValveAntiCheatSystem>
  <DisablePlayerMovePhysicsOptimization>false</DisablePlayerMovePhysicsOptimization>
  <DisableAntiSpeedHackDetection>false</DisableAntiSpeedHackDetection>
  <SpeedHackBias>1</SpeedHackBias>
  <UseBattlEye>false</UseBattlEye>
  <ForceRespawnDinos>false</ForceRespawnDinos>
  <EnableServerAdminLogs>true</EnableServerAdminLogs>
  <ServerAdminLogsIncludeTribeLogs>true</ServerAdminLogsIncludeTribeLogs>
  <ServerRCONOutputTribeLogs>false</ServerRCONOutputTribeLogs>
  <NotifyAdminCommandsInChat>true</NotifyAdminCommandsInChat>
  <MaxTribeLogs>100</MaxTribeLogs>
  <TribeLogDestroyedEnemyStructures>false</TribeLogDestroyedEnemyStructures>
  <ForceDirectX10>false</ForceDirectX10>
  <ForceShaderModel4>false</ForceShaderModel4>
  <ForceLowMemory>false</ForceLowMemory>
  <ForceNoManSky>false</ForceNoManSky>
  <UseAllAvailableCores>false</UseAllAvailableCores>
  <UseCache>false</UseCache>
  <AltSaveDirectoryName />
  <EnableWebAlarm>false</EnableWebAlarm>
  <WebAlarmKey />
  <WebAlarmUrl />
  <UseOldSaveFormat>false</UseOldSaveFormat>
  <UseNoMemoryBias>false</UseNoMemoryBias>
  <StasisKeepControllers>false</StasisKeepControllers>
  <CrossArkClusterId />
  <ClusterDirOverride>false</ClusterDirOverride>
  <AdditionalArgs />
  <LauncherArgsOverride>false</LauncherArgsOverride>
  <LauncherArgs />
  <EnableAutoBackup>true</EnableAutoBackup>
  <EnableAutoStart>false</EnableAutoStart>
  <EnableAutoUpdate>false</EnableAutoUpdate>
  <EnableAutoShutdown1>false</EnableAutoShutdown1>
  <AutoShutdownTime1>00:00</AutoShutdownTime1>
  <RestartAfterShutdown1>true</RestartAfterShutdown1>
  <UpdateAfterShutdown1>false</UpdateAfterShutdown1>
  <EnableAutoShutdown2>false</EnableAutoShutdown2>
  <AutoShutdownTime2>00:00</AutoShutdownTime2>
  <RestartAfterShutdown2>true</RestartAfterShutdown2>
  <UpdateAfterShutdown2>false</UpdateAfterShutdown2>
  <AutoRestartIfShutdown>false</AutoRestartIfShutdown>
  <AutoManagedMods>false</AutoManagedMods>
  <EnableHardcore>false</EnableHardcore>
  <EnablePVP>false</EnablePVP>
  <AllowCaveBuildingPvE>false</AllowCaveBuildingPvE>
  <DisableFriendlyFirePvP>true</DisableFriendlyFirePvP>
  <DisableFriendlyFirePvE>true</DisableFriendlyFirePvE>
  <DisableLootCrates>false</DisableLootCrates>
  <AllowCrateSpawnsOnTopOfStructures>true</AllowCrateSpawnsOnTopOfStructures>
  <EnableExtraStructurePreventionVolumes>true</EnableExtraStructurePreventionVolumes>
  <EnableDifficultyOverride>false</EnableDifficultyOverride>
  <OverrideOfficialDifficulty>4</OverrideOfficialDifficulty>
  <DifficultyOffset>1</DifficultyOffset>
  <MaxNumberOfPlayersInTribe>0</MaxNumberOfPlayersInTribe>
  <EnableTributeDownloads>false</EnableTributeDownloads>
  <PreventDownloadSurvivors>true</PreventDownloadSurvivors>
  <PreventDownloadItems>true</PreventDownloadItems>
  <PreventDownloadDinos>true</PreventDownloadDinos>
  <PreventUploadSurvivors>true</PreventUploadSurvivors>
  <PreventUploadItems>true</PreventUploadItems>
  <PreventUploadDinos>true</PreventUploadDinos>
  <NoTransferFromFiltering>false</NoTransferFromFiltering>
  <OverrideTributeCharacterExpirationSeconds>false</OverrideTributeCharacterExpirationSeconds>
  <OverrideTributeItemExpirationSeconds>false</OverrideTributeItemExpirationSeconds>
  <OverrideTributeDinoExpirationSeconds>false</OverrideTributeDinoExpirationSeconds>
  <OverrideMinimumDinoReuploadInterval>false</OverrideMinimumDinoReuploadInterval>
  <TributeCharacterExpirationSeconds>86400</TributeCharacterExpirationSeconds>
  <TributeItemExpirationSeconds>86400</TributeItemExpirationSeconds>
  <TributeDinoExpirationSeconds>86400</TributeDinoExpirationSeconds>
  <MinimumDinoReuploadInterval>43200</MinimumDinoReuploadInterval>
  <IncreasePvPRespawnInterval>false</IncreasePvPRespawnInterval>
  <IncreasePvPRespawnIntervalCheckPeriod>300</IncreasePvPRespawnIntervalCheckPeriod>
  <IncreasePvPRespawnIntervalMultiplier>1</IncreasePvPRespawnIntervalMultiplier>
  <IncreasePvPRespawnIntervalBaseAmount>60</IncreasePvPRespawnIntervalBaseAmount>
  <PreventOfflinePvP>true</PreventOfflinePvP>
  <PreventOfflinePvPInterval>900</PreventOfflinePvPInterval>
  <AutoPvETimer>false</AutoPvETimer>
  <AutoPvEUseSystemTime>false</AutoPvEUseSystemTime>
  <AutoPvEStartTimeSeconds>0</AutoPvEStartTimeSeconds>
  <AutoPvEStopTimeSeconds>0</AutoPvEStopTimeSeconds>
  <AllowTribeWarPvE>true</AllowTribeWarPvE>
  <AllowTribeWarCancelPvE>false</AllowTribeWarCancelPvE>
  <AllowTribeAlliances>true</AllowTribeAlliances>
  <AllowCustomRecipes>true</AllowCustomRecipes>
  <CustomRecipeEffectivenessMultiplier>1</CustomRecipeEffectivenessMultiplier>
  <CustomRecipeSkillMultiplier>1</CustomRecipeSkillMultiplier>
  <EnableDiseases>true</EnableDiseases>
  <NonPermanentDiseases>false</NonPermanentDiseases>
  <OverrideNPCNetworkStasisRangeScale>false</OverrideNPCNetworkStasisRangeScale>
  <NPCNetworkStasisRangeScalePlayerCountStart>70</NPCNetworkStasisRangeScalePlayerCountStart>
  <NPCNetworkStasisRangeScalePlayerCountEnd>120</NPCNetworkStasisRangeScalePlayerCountEnd>
  <NPCNetworkStasisRangeScalePercentEnd>0.5</NPCNetworkStasisRangeScalePercentEnd>
  <UseCorpseLocator>true</UseCorpseLocator>
  <PreventSpawnAnimations>false</PreventSpawnAnimations>
  <AllowUnlimitedRespecs>false</AllowUnlimitedRespecs>
  <AllowPlatformSaddleMultiFloors>false</AllowPlatformSaddleMultiFloors>
  <OxygenSwimSpeedStatMultiplier>1</OxygenSwimSpeedStatMultiplier>
  <SupplyCrateLootQualityMultiplier>10</SupplyCrateLootQualityMultiplier>
  <FishingLootQualityMultiplier>1</FishingLootQualityMultiplier>
  <EnableNoFishLoot>false</EnableNoFishLoot>
  <EnableGlobalVoiceChat>true</EnableGlobalVoiceChat>
  <EnableProximityChat>true</EnableProximityChat>
  <EnablePlayerLeaveNotifications>false</EnablePlayerLeaveNotifications>
  <EnablePlayerJoinedNotifications>false</EnablePlayerJoinedNotifications>
  <AllowCrosshair>true</AllowCrosshair>
  <AllowHUD>true</AllowHUD>
  <AllowThirdPersonView>true</AllowThirdPersonView>
  <AllowMapPlayerLocation>true</AllowMapPlayerLocation>
  <AllowPVPGamma>false</AllowPVPGamma>
  <AllowPvEGamma>false</AllowPvEGamma>
  <ShowFloatingDamageText>true</ShowFloatingDamageText>
  <AllowHitMarkers>true</AllowHitMarkers>
  <EnableFlyerCarry>true</EnableFlyerCarry>
  <XPMultiplier>1</XPMultiplier>
  <OverrideMaxExperiencePointsPlayer>6473540</OverrideMaxExperiencePointsPlayer>
  <PlayerDamageMultiplier>1</PlayerDamageMultiplier>
  <PlayerResistanceMultiplier>1</PlayerResistanceMultiplier>
  <PlayerCharacterWaterDrainMultiplier>0.3</PlayerCharacterWaterDrainMultiplier>
  <PlayerCharacterFoodDrainMultiplier>0.1</PlayerCharacterFoodDrainMultiplier>
  <PlayerCharacterStaminaDrainMultiplier>0.5</PlayerCharacterStaminaDrainMultiplier>
  <PlayerCharacterHealthRecoveryMultiplier>0.1</PlayerCharacterHealthRecoveryMultiplier>
  <PlayerHarvestingDamageMultiplier>1</PlayerHarvestingDamageMultiplier>
  <CraftingSkillBonusMultiplier>1</CraftingSkillBonusMultiplier>
  <OverrideMaxExperiencePointsDino>2525010</OverrideMaxExperiencePointsDino>
  <DinoDamageMultiplier>1</DinoDamageMultiplier>
  <TamedDinoDamageMultiplier>1</TamedDinoDamageMultiplier>
  <DinoResistanceMultiplier>1</DinoResistanceMultiplier>
  <TamedDinoResistanceMultiplier>1</TamedDinoResistanceMultiplier>
  <MaxTamedDinos>4000</MaxTamedDinos>
  <DinoCharacterFoodDrainMultiplier>0.5</DinoCharacterFoodDrainMultiplier>
  <DinoCharacterStaminaDrainMultiplier>0.1</DinoCharacterStaminaDrainMultiplier>
  <DinoCharacterHealthRecoveryMultiplier>0.1</DinoCharacterHealthRecoveryMultiplier>
  <DinoCountMultiplier>10</DinoCountMultiplier>
  <DinoHarvestingDamageMultiplier>3</DinoHarvestingDamageMultiplier>
  <DinoTurretDamageMultiplier>1</DinoTurretDamageMultiplier>
  <AllowRaidDinoFeeding>false</AllowRaidDinoFeeding>
  <RaidDinoCharacterFoodDrainMultiplier>1</RaidDinoCharacterFoodDrainMultiplier>
  <EnableAllowCaveFlyers>true</EnableAllowCaveFlyers>
  <AllowFlyingStaminaRecovery>true</AllowFlyingStaminaRecovery>
  <PreventMateBoost>false</PreventMateBoost>
  <DisableDinoDecayPvE>false</DisableDinoDecayPvE>
  <DisableDinoDecayPvP>true</DisableDinoDecayPvP>
  <AutoDestroyDecayedDinos>false</AutoDestroyDecayedDinos>
  <PvEDinoDecayPeriodMultiplier>1</PvEDinoDecayPeriodMultiplier>
  <ForceFlyerExplosives>false</ForceFlyerExplosives>
  <AllowMultipleAttachedC4>false</AllowMultipleAttachedC4>
  <DisableDinoRiding>false</DisableDinoRiding>
  <DisableDinoTaming>false</DisableDinoTaming>
  <MaxPersonalTamedDinos>500</MaxPersonalTamedDinos>
  <MatingIntervalMultiplier>1</MatingIntervalMultiplier>
  <EggHatchSpeedMultiplier>0.5</EggHatchSpeedMultiplier>
  <BabyMatureSpeedMultiplier>0.1</BabyMatureSpeedMultiplier>
  <BabyFoodConsumptionSpeedMultiplier>0.5</BabyFoodConsumptionSpeedMultiplier>
  <DisableImprintDinoBuff>false</DisableImprintDinoBuff>
  <AllowAnyoneBabyImprintCuddle>true</AllowAnyoneBabyImprintCuddle>
  <BabyImprintingStatScaleMultiplier>1</BabyImprintingStatScaleMultiplier>
  <BabyCuddleIntervalMultiplier>0.5</BabyCuddleIntervalMultiplier>
  <BabyCuddleGracePeriodMultiplier>1</BabyCuddleGracePeriodMultiplier>
  <BabyCuddleLoseImprintQualitySpeedMultiplier>0.1</BabyCuddleLoseImprintQualitySpeedMultiplier>
  <TamingSpeedMultiplier>10</TamingSpeedMultiplier>
  <HarvestAmountMultiplier>1</HarvestAmountMultiplier>
  <ResourcesRespawnPeriodMultiplier>0.1</ResourcesRespawnPeriodMultiplier>
  <ResourceNoReplenishRadiusPlayers>1</ResourceNoReplenishRadiusPlayers>
  <ResourceNoReplenishRadiusStructures>1</ResourceNoReplenishRadiusStructures>
  <HarvestHealthMultiplier>1</HarvestHealthMultiplier>
  <UseOptimizedHarvestingHealth>false</UseOptimizedHarvestingHealth>
  <ClampResourceHarvestDamage>false</ClampResourceHarvestDamage>
  <ClampItemSpoilingTimes>false</ClampItemSpoilingTimes>
  <DayCycleSpeedScale>1</DayCycleSpeedScale>
  <DayTimeSpeedScale>1</DayTimeSpeedScale>
  <NightTimeSpeedScale>1</NightTimeSpeedScale>
  <GlobalSpoilingTimeMultiplier>1</GlobalSpoilingTimeMultiplier>
  <GlobalItemDecompositionTimeMultiplier>1</GlobalItemDecompositionTimeMultiplier>
  <GlobalCorpseDecompositionTimeMultiplier>1</GlobalCorpseDecompositionTimeMultiplier>
  <CropDecaySpeedMultiplier>1</CropDecaySpeedMultiplier>
  <CropGrowthSpeedMultiplier>1</CropGrowthSpeedMultiplier>
  <LayEggIntervalMultiplier>1</LayEggIntervalMultiplier>
  <PoopIntervalMultiplier>1</PoopIntervalMultiplier>
  <HairGrowthSpeedMultiplier>1</HairGrowthSpeedMultiplier>
  <CraftXPMultiplier>1</CraftXPMultiplier>
  <GenericXPMultiplier>1</GenericXPMultiplier>
  <HarvestXPMultiplier>1</HarvestXPMultiplier>
  <KillXPMultiplier>1</KillXPMultiplier>
  <SpecialXPMultiplier>1</SpecialXPMultiplier>
  <StructureResistanceMultiplier>0.5</StructureResistanceMultiplier>
  <StructureDamageMultiplier>1</StructureDamageMultiplier>
  <StructureDamageRepairCooldown>180</StructureDamageRepairCooldown>
  <PvPStructureDecay>false</PvPStructureDecay>
  <PvPZoneStructureDamageMultiplier>6</PvPZoneStructureDamageMultiplier>
  <MaxStructuresVisible>10500</MaxStructuresVisible>
  <PerPlatformMaxStructuresMultiplier>1</PerPlatformMaxStructuresMultiplier>
  <MaxPlatformSaddleStructureLimit>50</MaxPlatformSaddleStructureLimit>
  <OverrideStructurePlatformPrevention>false</OverrideStructurePlatformPrevention>
  <FlyerPlatformAllowUnalignedDinoBasing>false</FlyerPlatformAllowUnalignedDinoBasing>
  <PvEAllowStructuresAtSupplyDrops>false</PvEAllowStructuresAtSupplyDrops>
  <EnableStructureDecayPvE>false</EnableStructureDecayPvE>
  <PvEStructureDecayDestructionPeriod>0</PvEStructureDecayDestructionPeriod>
  <PvEStructureDecayPeriodMultiplier>1</PvEStructureDecayPeriodMultiplier>
  <AutoDestroyOldStructuresMultiplier>0</AutoDestroyOldStructuresMultiplier>
  <ForceAllStructureLocking>false</ForceAllStructureLocking>
  <PassiveDefensesDamageRiderlessDinos>false</PassiveDefensesDamageRiderlessDinos>
  <EnableAutoDestroyStructures>false</EnableAutoDestroyStructures>
  <OnlyAutoDestroyCoreStructures>false</OnlyAutoDestroyCoreStructures>
  <OnlyDecayUnsnappedCoreStructures>false</OnlyDecayUnsnappedCoreStructures>
  <FastDecayUnsnappedCoreStructures>false</FastDecayUnsnappedCoreStructures>
  <DestroyUnconnectedWaterPipes>false</DestroyUnconnectedWaterPipes>
  <DisableStructurePlacementCollision>false</DisableStructurePlacementCollision>
  <EnableFastDecayInterval>false</EnableFastDecayInterval>
  <FastDecayInterval>43200</FastDecayInterval>
  <OnlyAllowSpecifiedEngrams>false</OnlyAllowSpecifiedEngrams>
  <EnableExclusiveJoin>false</EnableExclusiveJoin>
  <PGM_Enabled>false</PGM_Enabled>
  <PGM_Name />
  <PGM_Terrain>
    <MapSeed>999</MapSeed>
    <LandscapeRadius>1</LandscapeRadius>
    <WaterFrequency>5</WaterFrequency>
    <MountainsFrequency>12</MountainsFrequency>
    <MountainsSlope>1.8</MountainsSlope>
    <MountainsHeight>1.25</MountainsHeight>
    <TurbulencePower>0.0125</TurbulencePower>
    <ShoreSlope>1</ShoreSlope>
    <WaterLevel>-0.72</WaterLevel>
    <ShoreLineEnd>-0.715</ShoreLineEnd>
    <GrassDensity>1</GrassDensity>
    <JungleGrassDensity>0.02</JungleGrassDensity>
    <OceanFloorLevel>-1</OceanFloorLevel>
    <SnowBiomeSize>0.3</SnowBiomeSize>
    <RedWoodBiomeSize>0.075</RedWoodBiomeSize>
    <MountainBiomeStart>-0.55</MountainBiomeStart>
    <MountainsTreeDensity>0.01</MountainsTreeDensity>
    <JungleBiomeStart>-0.65</JungleBiomeStart>
    <IslandBorderCurveExponent>4</IslandBorderCurveExponent>
    <MaxSpawnPointHeight>0.1</MaxSpawnPointHeight>
    <MountainGrassDensity>0.05</MountainGrassDensity>
    <SnowMountainGrassDensity>0.15</SnowMountainGrassDensity>
    <SnowGrassDensity>0.25</SnowGrassDensity>
    <UnderwaterObjectsDensity>0.5</UnderwaterObjectsDensity>
    <SnowMountainsTreeDensity>0.01</SnowMountainsTreeDensity>
    <TreeDensity>0.003</TreeDensity>
    <JungleTreeDensity>0.66</JungleTreeDensity>
    <RedWoodTreeDensity>0.35</RedWoodTreeDensity>
    <SnowTreeDensity>1</SnowTreeDensity>
    <RedwoodGrassDensity>0.1</RedwoodGrassDensity>
    <ShoreTreeDensity>0.05</ShoreTreeDensity>
    <SnowShoreTreeDensity>0.025</SnowShoreTreeDensity>
    <DeepWaterBiomesDepth>-0.24</DeepWaterBiomesDepth>
    <InlandWaterObjectsDensity>0.5</InlandWaterObjectsDensity>
    <ShorelineStartOffset>0.01</ShorelineStartOffset>
    <ShorelineThickness>0.0015</ShorelineThickness>
    <TreesGroundSlopeAccuracy>0.5</TreesGroundSlopeAccuracy>
    <ErosionSteps>4</ErosionSteps>
    <ErosionStrength>0.75</ErosionStrength>
    <DepositionStrength>0.5</DepositionStrength>
    <MountainGeneralTreesPercent>0.1</MountainGeneralTreesPercent>
    <SnowBiomeLocation>
      <X>0.2</X>
      <Y>0.2</Y>
    </SnowBiomeLocation>
    <RedWoodForestBiomeLocation>
      <X>0.5</X>
      <Y>0.5</Y>
    </RedWoodForestBiomeLocation>
    <NorthRegion1Start>
      <X>0.25</X>
      <Y>0</Y>
    </NorthRegion1Start>
    <NorthRegion1End>
      <X>0.416</X>
      <Y>0.5</Y>
    </NorthRegion1End>
    <NorthRegion2Start>
      <X>0.416</X>
      <Y>0</Y>
    </NorthRegion2Start>
    <NorthRegion2End>
      <X>0.582</X>
      <Y>0.5</Y>
    </NorthRegion2End>
    <NorthRegion3Start>
      <X>0.582</X>
      <Y>0</Y>
    </NorthRegion3Start>
    <NorthRegion3End>
      <X>0.75</X>
      <Y>0</Y>
    </NorthRegion3End>
    <SouthRegion1Start>
      <X>0.25</X>
      <Y>0.5</Y>
    </SouthRegion1Start>
    <SouthRegion1End>
      <X>0.416</X>
      <Y>1</Y>
    </SouthRegion1End>
    <SouthRegion2Start>
      <X>0.416</X>
      <Y>0.5</Y>
    </SouthRegion2Start>
    <SouthRegion2End>
      <X>0.582</X>
      <Y>1</Y>
    </SouthRegion2End>
    <SouthRegion3Start>
      <X>0.582</X>
      <Y>0.5</Y>
    </SouthRegion3Start>
    <SouthRegion3End>
      <X>0.75</X>
      <Y>1</Y>
    </SouthRegion3End>
    <EastRegion1Start>
      <X>0.75</X>
      <Y>0</Y>
    </EastRegion1Start>
    <EastRegion1End>
      <X>1</X>
      <Y>0.333</Y>
    </EastRegion1End>
    <EastRegion2Start>
      <X>0.75</X>
      <Y>0.333</Y>
    </EastRegion2Start>
    <EastRegion2End>
      <X>1</X>
      <Y>0.666</Y>
    </EastRegion2End>
    <EastRegion3Start>
      <X>0.75</X>
      <Y>0.666</Y>
    </EastRegion3Start>
    <EastRegion3End>
      <X>1</X>
      <Y>1</Y>
    </EastRegion3End>
    <WestRegion1Start>
      <X>0</X>
      <Y>0</Y>
    </WestRegion1Start>
    <WestRegion1End>
      <X>0.25</X>
      <Y>0.333</Y>
    </WestRegion1End>
    <WestRegion2Start>
      <X>0</X>
      <Y>0.333</Y>
    </WestRegion2Start>
    <WestRegion2End>
      <X>0.25</X>
      <Y>0.666</Y>
    </WestRegion2End>
    <WestRegion3Start>
      <X>0</X>
      <Y>0.666</Y>
    </WestRegion3Start>
    <WestRegion3End>
      <X>0.25</X>
      <Y>1</Y>
    </WestRegion3End>
    <TerrainScaleMultiplier>
      <X>1</X>
      <Y>1</Y>
      <Z>1</Z>
    </TerrainScaleMultiplier>
  </PGM_Terrain>
  <SOTF_Enabled>false</SOTF_Enabled>
  <SOTF_DisableDeathSPectator>false</SOTF_DisableDeathSPectator>
  <SOTF_OnlyAdminRejoinAsSpectator>false</SOTF_OnlyAdminRejoinAsSpectator>
  <SOTF_GamePlayLogging>false</SOTF_GamePlayLogging>
  <SOTF_OutputGameReport>false</SOTF_OutputGameReport>
  <SOTF_MaxNumberOfPlayersInTribe>2</SOTF_MaxNumberOfPlayersInTribe>
  <SOTF_BattleNumOfTribesToStartGame>15</SOTF_BattleNumOfTribesToStartGame>
  <SOTF_TimeToCollapseROD>9000</SOTF_TimeToCollapseROD>
  <SOTF_BattleAutoStartGameInterval>60</SOTF_BattleAutoStartGameInterval>
  <SOTF_BattleAutoRestartGameInterval>45</SOTF_BattleAutoRestartGameInterval>
  <SOTF_BattleSuddenDeathInterval>300</SOTF_BattleSuddenDeathInterval>
  <SOTF_NoEvents>false</SOTF_NoEvents>
  <SOTF_NoBosses>false</SOTF_NoBosses>
  <SOTF_BothBosses>false</SOTF_BothBosses>
  <SOTF_EvoEventInterval>1</SOTF_EvoEventInterval>
  <SOTF_RingStartTime>1000</SOTF_RingStartTime>
  <RCONWindowExtents>
    <Location>
      <X>0</X>
      <Y>0</Y>
    </Location>
    <Size>
      <Width>0</Width>
      <Height>0</Height>
    </Size>
    <X>0</X>
    <Y>0</Y>
    <Width>0</Width>
    <Height>0</Height>
  </RCONWindowExtents>
</ArkServerProfile>